"""
Train a ResUNet experiment for leucaena segmentation.

Typical workflow
----------------
1. Run ``python prep-data.py`` to populate ``prepared/``.
2. Run ``python train.py -e <N>`` where ``N`` matches ``conf/model_<N>.py``
   (e.g. ``-e 1`` → optical-only, ``-e 2`` early fusion, ``-e 3`` late fusion).
3. Checkpoints and logs live under ``experiments/exp_<N>/``.

Notes for code readers
----------------------
- Training ``print`` output goes to the terminal **and** ``experiments/.../logs/train_<e>.txt``
  (see ``Tee`` below). Progress bars use stderr so the log file stays readable.
- The model receives a *tuple* ``(optical_tensor, lidar_tensor)``; see ``utils/dataloader.py``.
- ``-c`` / ``--continue-train`` reloads ``models/model.pt`` (same experiment folder).
"""
import argparse       # parses command-line arguments (e.g. -e 1 for experiment 1)
import pathlib        # object-oriented filesystem paths
import importlib      # dynamic import — lets us load conf/model_1.py, model_2.py, etc. at runtime
from conf import default, general, paths
import os
import time
import sys

# multiprocessing.Process: could be used to run multiple training jobs in parallel
# (e.g. train model_1 and model_2 simultaneously on a multi-GPU machine).
# Not active in the current single-model loop but left here as a starting point.
from multiprocessing import Process

from utils.dataloader import TreeTrainDataSet, PatchFileDataset
from torch.utils.data import DataLoader  # wraps a Dataset and produces batches automatically
import torch
from torch import nn

# ResUnet: imported for type reference and quick testing in a Python shell.
# In the normal workflow the model is loaded dynamically via importlib below.
from models.resunet import ResUnet

from utils.ops import count_parameters
from tqdm import tqdm   # progress bar for the training loop
from utils.trainer import train_loop, val_loop, EarlyStop, val_sample_image
from utils.training_log import MetricsLogger

# MultiStepLR: reduces the learning rate at specific epoch milestones (step schedule).
# ExponentialLR: multiplies the LR by gamma every epoch (smoother decay).
# Both are imported so you can switch between them by commenting/uncommenting below.
from torch.optim.lr_scheduler import MultiStepLR, ExponentialLR

parser = argparse.ArgumentParser(
    description='Train one ResUNet experiment (see conf/model_<e>.py for architecture).'
)

parser.add_argument( # Experiment number
    '-e', '--experiment',
    type = int,
    default = 9,
    help = 'The number of the experiment'
)

parser.add_argument( # batch size
    '-b', '--batch-size',
    type = int,
    default = default.BATCH_SIZE,
    help = 'The number of samples of each batch'
)

parser.add_argument( # Number of models to be trained
    '-n', '--number-models',
    type = int,
    default = 1,
    help = 'The number models to be trained from the scratch'
)

parser.add_argument( # Experiment path
    '-c', '--continue-train',
    type = bool,
    default = False,
    help = 'Continue previous training'
)

parser.add_argument( # Experiment path
    '-x', '--experiments-path',
    type = pathlib.Path,
    default = paths.PATH_EXPERIMENTS,
    help = 'The patch to data generated by all experiments'
)

parser.add_argument( # Data Augmentation
    '-a', '--data-aug',
    type = bool,
    default = True,
    help = 'Use or not data augmentation'
)

parser.add_argument( # Patch source: legacy scene (prep-data.py) or new tile-based (prep-patches-from-tiles.py)
    '--patch-source',
    choices=('scene', 'file'),
    default='scene',
    help=(
        'Where training patches come from. "scene" (default) uses prepared/*.npy '
        'produced by prep-data.py; "file" reads individual patches via the '
        'manifest produced by prep-patches-from-tiles.py.'
    ),
)

parser.add_argument(
    '--manifest',
    type=pathlib.Path,
    default=paths.PATH_PATCHES_MANIFEST,
    help='Manifest CSV used when --patch-source file (default: %(default)s)',
)

parser.add_argument(
    '--cache-patches',
    action='store_true',
    help='Load all patches of each split into RAM once (~2 GiB for ~6k patches). '
    'Much faster epochs; use when you have free memory.',
)

args = parser.parse_args()


class Tee:
    """Write stdout to the terminal and to the experiment log file."""

    def __init__(self, *streams):
        self.streams = streams

    def write(self, data):
        for stream in self.streams:
            stream.write(data)
            stream.flush()

    def flush(self):
        for stream in self.streams:
            stream.flush()


# Per-experiment folder layout mirrors the original tree_fusion project.
exp_path = os.path.join(str(args.experiments_path), f'exp_{args.experiment}')
logs_path = os.path.join(exp_path, 'logs')
models_path = os.path.join(exp_path, 'models')
visual_path = os.path.join(exp_path, 'visual')
predicted_path = os.path.join(exp_path, 'predicted')
results_path = os.path.join(exp_path, 'results')
for _path in (logs_path, models_path, visual_path, predicted_path, results_path):
    os.makedirs(_path, exist_ok=True)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

outfile = os.path.join(logs_path, f'train_{args.experiment}.txt')
_log_file = open(outfile, 'w', encoding='utf-8')
_stdout_saved = sys.stdout
_stderr_saved = sys.stderr
sys.stdout = Tee(_stdout_saved, _log_file)
sys.stderr = Tee(_stderr_saved, _log_file)
try:
    print(f'Logging to {outfile} (terminal + file)')
    # Dynamic import: experiment id must match an existing conf/model_<id>.py
    model_m = importlib.import_module(f'conf.model_{args.experiment}')
    model, lidar_bands = model_m.get_model()
    # Optional flag: model configs can set COMPUTE_NDVI = True to append
    # NDVI as an extra optical channel on-the-fly in PatchFileDataset.
    compute_ndvi = getattr(model_m, 'COMPUTE_NDVI', False)

    print(f'{model.__class__.__name__}')
    print(f'Patch source: {args.patch_source}')
    print(f'Compute NDVI on-the-fly: {compute_ndvi}')

    if args.patch_source == 'file':
        manifest_path = str(args.manifest)
        print(f'Manifest: {manifest_path}')
        ds_train = PatchFileDataset(
            manifest_path=manifest_path,
            split='train',
            device=device,
            data_aug=args.data_aug,
            lidar_bands=lidar_bands,
            cache_in_ram=args.cache_patches,
            compute_ndvi=compute_ndvi,
        )
        ds_val = PatchFileDataset(
            manifest_path=manifest_path,
            split='val',
            device=device,
            data_aug=False,
            lidar_bands=lidar_bands,
            cache_in_ram=args.cache_patches,
            compute_ndvi=compute_ndvi,
        )
    else:
        path_to_patches_train = os.path.join(paths.PREPARED_PATH, 'train_patches.npy')
        path_to_patches_val = os.path.join(paths.PREPARED_PATH, 'val_patches.npy')

        ds_train = TreeTrainDataSet(path_to_patches = path_to_patches_train, device = device, data_aug=args.data_aug, lidar_bands = lidar_bands)
        ds_val = TreeTrainDataSet(path_to_patches = path_to_patches_val, device = device, lidar_bands = lidar_bands)

    dataloader_train = DataLoader(ds_train, batch_size=args.batch_size, shuffle=True)
    dataloader_val = DataLoader(ds_val, batch_size=args.batch_size, shuffle=False)

    model.to(device)

    print(f'Model trainable parameters: {count_parameters(model):,}')

    torch.set_num_threads(8)

    # ResUNetClassifier applies Softmax on outputs; PyTorch CE typically expects raw logits.
    # If you change the classifier head, align loss + metrics accordingly.
    loss_fn = nn.CrossEntropyLoss(
        ignore_index=general.IGNORE_INDEX,
        weight=torch.tensor(general.CLASSES_WEIGHTS).to(device)
    )
    optimizer = torch.optim.Adam(model.parameters(), lr=general.LEARNING_RATE, betas=general.LEARNING_RATE_BETAS)
    model_path = os.path.join(models_path, 'model.pt')
    early_stop = EarlyStop(
        train_patience=general.EARLY_STOP_PATIENCE,
        path_to_save = model_path,
        min_delta = general.EARLY_STOP_MIN_DELTA,
        min_epochs = general.EARLY_STOP_MIN_EPOCHS
        )

    if args.continue_train:
        model.load_state_dict(torch.load(model_path))

    t0 = time.perf_counter()
    
    print(f'Model: {model}')
    print(f'Train batch size: {args.batch_size}')
    print(f'Data augmentation: {args.data_aug}')
    print(f'Loss fn: {loss_fn}')
    print(f'Optmizer :{optimizer}')
    print(f'Paticence :{general.EARLY_STOP_PATIENCE}')
    print(f'Early Stop Min Delta :{general.EARLY_STOP_MIN_DELTA}')
    print(f'Early Stop Min Epochs :{general.EARLY_STOP_MIN_EPOCHS}')
    print(f'Scheduler Gamma :{general.LEARNING_RATE_SCHEDULER_GAMMA}')
    print(f'LR Milestones :{general.LEARNING_RATE_SCHEDULER_MILESTONES}')

    # MultiStepLR drops the LR by `gamma` at each epoch in MILESTONES — good when you
    # know the model needs larger steps early and smaller steps after a certain epoch.
    '''scheduler = MultiStepLR(
        optimizer, 
        milestones = general.LEARNING_RATE_SCHEDULER_MILESTONES,
        gamma=general.LEARNING_RATE_SCHEDULER_GAMMA,
        verbose = True
        )'''

    # ExponentialLR multiplies the LR by gamma every epoch (gentler, continuous decay).
    scheduler = ExponentialLR(
        optimizer, 
        gamma=general.LEARNING_RATE_SCHEDULER_GAMMA,
        verbose = True
        )

    metrics_logger = MetricsLogger(logs_path)
    metrics_logger.write_config({
        'experiment': args.experiment,
        'patch_source': args.patch_source,
        'manifest': str(args.manifest) if args.patch_source == 'file' else None,
        'batch_size': args.batch_size,
        'data_augmentation': args.data_aug,
        'cache_patches_in_ram': args.cache_patches,
        'max_epochs': general.MAX_EPOCHS,
        'learning_rate': general.LEARNING_RATE,
        'early_stop_patience': general.EARLY_STOP_PATIENCE,
        'device': device,
    })
    print(f'Metrics CSV: {metrics_logger.metrics_path}')

    for t in range(general.MAX_EPOCHS):
        epoch = t + 1
        print(f"-------------------------------\nEpoch {epoch}")
        model.train()
        train_loss, train_f1 = train_loop(dataloader_train, model, loss_fn, optimizer)
        model.eval()
        val_loss, val_f1 = val_loop(dataloader_val, model, loss_fn)
        val_sample_image(dataloader_val, model, visual_path, t)
        stop, checkpoint_saved = early_stop.testEpoch(model=model, val_value=val_loss)
        lr = optimizer.param_groups[0]['lr']
        metrics_logger.log_epoch(
            epoch=epoch,
            train_loss=train_loss,
            train_f1=train_f1,
            val_loss=val_loss,
            val_f1=val_f1,
            learning_rate=lr,
            best_val_loss=early_stop.better_value,
            epochs_no_improve=early_stop.no_change_epochs,
            checkpoint_saved=checkpoint_saved,
        )
        if stop:
            print(f'Early stopping at epoch {epoch}.')
            break
        scheduler.step()
    metrics_logger.close()
    print(f'Training time: {(time.perf_counter() - t0)/60:.1f} mins')
    print(f'Plot curves: python -m utils.plot_training -e {args.experiment}')
finally:
    sys.stdout = _stdout_saved
    sys.stderr = _stderr_saved
    _log_file.close()
