"""
Filesystem layout for raw inputs and experiment outputs.

Point ``PATH_*`` entries at your local GeoTIFFs / GeoJSON before running ``prep-data.py``.

Machine-specific host paths belong in ``.env`` (gitignored). Copy ``.env.example``
to ``.env`` and edit there — never commit real paths to the repository.
"""
import os


def _env(key: str, default: str) -> str:
    return os.environ.get(key, default)

# --- Optical imagery (4-band GeoTIFF: B, G, R, NIR) ---
PATH_OPTICAL = os.path.join('data', 'optical.tif')

# --- LiDAR raster products (multi-band GeoTIFF: CHM, intensity, ...) ---
# Pre-process your LAS/LAZ point cloud into raster bands before using this pipeline.
# Tools: PDAL, LAStools, CloudCompare, or WhiteboxTools.
PATH_LIDAR = os.path.join('data', 'lidar.tif')

# --- Optional: separate train/test mask files ---
# If provided, these override PATH_MASKS and skip the automatic train/test split.
PATH_TRAIN_MASKS = None
PATH_TEST_MASKS = None

# --- Experiment outputs ---
PATH_EXPERIMENTS = os.path.join('experiments')

# --- Prepared numpy arrays (generated by prep-data.py) ---
PREPARED_PATH = 'prepared'

# --- Masks + tile-based patch pipeline (prep-patches-from-tiles.py) ---
# Set LEUCAENA_MASKS_PATH in .env for Docker; default is data/masks.geojson in the repo.
PATH_MASKS = _env('LEUCAENA_MASKS_PATH', os.path.join('data', 'masks.geojson'))
PATH_TILES_DIR = _env('LEUCAENA_TILES_DIR', os.path.join(os.sep, 'data', 'rgbir'))
PATH_PATCHES_DIR = _env('LEUCAENA_PATCHES_DIR', os.path.join(PREPARED_PATH, 'patches'))
PATH_PATCHES_MANIFEST = os.path.join(PATH_PATCHES_DIR, 'manifest.csv')

# --- LiDAR tile-based pipeline (prep-lidar-rasters.py) ---
# PATH_LAZ_DIR  : folder with raw .laz/.las point clouds (input to prep-lidar-rasters.py).
# PATH_LIDAR_DIR: folder with the resulting 2-band GeoTIFFs (CHM, INTENSITY) that
#                 prep-patches-from-tiles.py reads alongside RGBN tiles.
PATH_LAZ_DIR = _env('LEUCAENA_LAZ_DIR', os.path.join(os.sep, 'data', 'laz'))
PATH_LIDAR_DIR = _env('LEUCAENA_LIDAR_DIR', os.path.join(os.sep, 'data', 'lidar'))
PATH_LIDAR_MANIFEST = os.path.join(PATH_LIDAR_DIR, 'lidar_manifest.csv')
