"""
Filesystem layout for raw inputs and experiment outputs.

Point ``PATH_*`` entries at your local GeoTIFFs / GeoJSON before running ``prep-data.py``.
"""
import os

# --- Optical imagery (4-band GeoTIFF: B, G, R, NIR) ---
PATH_OPTICAL = os.path.join('data', 'optical.tif')

# --- LiDAR raster products (multi-band GeoTIFF: CHM, intensity, ...) ---
# Pre-process your LAS/LAZ point cloud into raster bands before using this pipeline.
# Tools: PDAL, LAStools, CloudCompare, or WhiteboxTools.
PATH_LIDAR = os.path.join('data', 'lidar.tif')

# --- Mask polygons exported from leucaena.earth (GeoJSON) ---
PATH_MASKS = os.path.join('data', 'masks.geojson')

# --- Optional: separate train/test mask files ---
# If provided, these override PATH_MASKS and skip the automatic train/test split.
PATH_TRAIN_MASKS = None
PATH_TEST_MASKS = None

# --- Experiment outputs ---
PATH_EXPERIMENTS = os.path.join('experiments')

# --- Prepared numpy arrays (generated by prep-data.py) ---
PREPARED_PATH = 'prepared'

# --- Tile-based patch pipeline (prep-patches-from-tiles.py) ---
# Default tiles dir is /data/rgbir inside Docker (see docker-compose.yml:
# C:\Users\mathe\Downloads\rgbir on the host). Patches are written under
# prepared/patches/ in this repo (also on C:, via OneDrive path).
PATH_TILES_DIR = os.path.join(os.sep, 'data', 'rgbir')
PATH_PATCHES_DIR = os.path.join(PREPARED_PATH, 'patches')
PATH_PATCHES_MANIFEST = os.path.join(PATH_PATCHES_DIR, 'manifest.csv')
